theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    footer: "/assets/images/logof.svg"
  summary:
    position: content
  search:
    active: false
  programs:
    related_posts:
      quantity: 3